Modify multi.yml for KPM patch application

diff --git a/.github/workflows/multi.yml b/.github/workflows/multi.yml
--- a/.github/workflows/multi.yml
+++ b/.github/workflows/multi.yml
@@ -168,9 +168,6 @@ jobs:
           CONFIG_KPM=y
           CONFIG_KSU_SUSFS_SUS_SU=n
           CONFIG_KSU_SYSCALL_HOOK=n
-          CONFIG_KPROBES=y
-          CONFIG_KPROBE_EVENTS=y
-          CONFIG_OVERLAY_FS=y
           CONFIG_KSU_SUSFS=y
           CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
           CONFIG_KSU_SUSFS_SUS_PATH=y
@@ -183,13 +180,20 @@ jobs:
           CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n
           CONFIG_KSU_SUSFS_TRY_UMOUNT=y
           CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
-          CONFIG_KSU_SUSFS_ENABLE_LOG=y
           CONFIG_KSU_SUSFS_SPOOF_UNAME=y
+          CONFIG_KSU_SUSFS_ENABLE_LOG=y
           CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
-          CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
+          CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=n
           CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
           CONFIG_KSU_MANUAL_HOOK=n
           CONFIG_KSU_HAS_MANUAL_HOOK=n
+
+          
+          # GKI requires kprobes symbols to be present
+          CONFIG_KPROBES=y
+          CONFIG_HAVE_KPROBES=y
+          CONFIG_KRETPROBES=y
+          CONFIG_KPROBE_EVENTS=y
 
           # --- IDENTITY & VERSIONING ---
           CONFIG_LOCALVERSION_AUTO=n          
@@ -226,6 +230,25 @@ jobs:
           LTO=thin LLVM=1 LLVM_IAS=1 \
           KCFLAGS="-O3 -Wno-error=implicit-function-declaration -Wno-error=unused-command-line-argument" \
           BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
+
+      - name: Apply KPM Patch
+        working-directory: gki/out/android12-5.10/dist
+        run: |
+          if [ -f Image ]; then
+            echo "✅ Image found, applying KPM patch..."
+            curl -LSs "https://github.com/Kingfinik98/SukiSU_patch/raw/refs/heads/main/kpm/patch_linux" -o patch
+            chmod 777 patch
+            ./patch
+            if [ -f oImage ]; then
+              mv -f oImage Image
+              ls -lh Image
+            else
+              echo "Error: oImage not found!"
+              exit 1
+            fi
+          else
+            echo "Image file not found. Skipping KPM patch."
+          fi
 
       - name: Packaging anykernel & Release
         if: success()
