Update van van.yml

diff --git a/.github/workflows/van van.yml b/.github/workflows/van van.yml
--- a/.github/workflows/van van.yml
+++ b/.github/workflows/van van.yml
@@ -73,6 +73,20 @@ jobs:
           curl -L "https://github.com/ramabondanp/android_kernel_common-5.10/commit/4fe04b60009e.patch" -o infinix_cam.patch
           patch -p1 < infinix_cam.patch || echo "✅ Patch kamera sudah tertanam."
 
+      - name: Apply multimanager 
+        working-directory: gki/common
+        run: |
+          echo "setup multimanager ah"
+          curl -LSs "https://raw.githubusercontent.com/Kingfinik98/ReSukiSU/refs/heads/main/kernel/setup.sh" | bash -s main
+          git clone https://gitlab.com/simonpunk/susfs4ksu/ -b gki-android12-5.10 sus
+          rm -rf sus/.git
+          susfs=sus/kernel_patches
+          cp -r $susfs/fs .
+          cp -r $susfs/include .
+          cp -r $susfs/50_add_susfs_in_gki-android12-5.10.patch .
+          patch -p1 < 50_add_susfs_in_gki-android12-5.10.patch
+          echo "[✓] SUSFS patched"
+          
       # --- Critical Fixes ---
       - name: Apply Critical Fixes
         working-directory: gki/common
@@ -109,6 +123,7 @@ jobs:
           
           echo "⚙️ Injecting Configuration..."
           cat >> $TARGET_CONFIG <<EOF
+          CONFIG_KSU_MULTI_MANAGER_SUPPORT=y
           CONFIG_STACKPROTECTOR_PER_TASK=n
           CONFIG_TCP_CONG_BBR=y
           CONFIG_TCP_CONG_ADVANCED=y
@@ -177,6 +192,25 @@ jobs:
           KCFLAGS="-O3 -Wno-error=implicit-function-declaration -Wno-error=unused-command-line-argument" \
           BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
 
+      - name: Apply KPM Patch
+        working-directory: gki/out/android12-5.10/dist
+        run: |
+          if [ -f Image ]; then
+            echo "Image found, applying KPM patch..."
+            curl -LSs "https://github.com/Kingfinik98/SukiSU_patch/raw/refs/heads/main/kpm/patch_linux" -o patch
+            chmod 777 patch
+            ./patch
+            if [ -f oImage ]; then
+              mv -f oImage Image
+              ls -lh Image
+            else
+              echo "Error: oImage not found!"
+              exit 1
+            fi
+          else
+            echo "Image file not found. Skipping KPM patch."
+          fi
+
       - name: Packaging anykernel & Release
         if: success()
         env:
@@ -191,7 +225,7 @@ jobs:
           
           # HARDCODED VARIANT
           VARIANT="vanilla"
-          ZIP_NAME="RE-GKI-zixine-elysium-inline-${VARIANT}-${DATE}.zip"
+          ZIP_NAME="RE-GKI-zixine-elysium-inline-multi-${VARIANT}-${DATE}.zip"
           
           AK3_REPO="https://github.com/zixine/anykernel" 
           git clone -q --depth=1 "$AK3_REPO" -b main anykernel
